name: 'MK: destellos de fiesta'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e55c45d9-f1bb-46cb-baf8-593e2d011472.png
layout_spectrum: 0.9464043771672852
typography_spectrum: 0.6442045146080236
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: mkdestellosdefiesta
color:
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
  brandStrength: 0.3426064591818707
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
title: 'Venta, alquiler y transformación de trajes regionales y fiesta'
author:
  name: Ruben
  url: ''
  email: ruben.mkddf@gmail.com
content_rating:
  adult: false
